export const COUNTRIES = [
  { id: "ARG", name: "Argentina" },
  { id: "BLZ", name: "Belize" },
  { id: "BOL", name: "Bolivia" },
  { id: "BRA", name: "Brazil" },
  { id: "CHL", name: "Chile" },
  { id: "COL", name: "Colombia" },
  { id: "CRI", name: "Costa Rica" },
  { id: "ECU", name: "Ecuador" },
  { id: "SLV", name: "El Salvador" },
  { id: "GTM", name: "Guatemala" },
  { id: "GUY", name: "Guyana" },
  { id: "HND", name: "Honduras" },
  { id: "MEX", name: "Mexico" },
  { id: "NIC", name: "Nicaragua" },
  { id: "PAN", name: "Panama" },
  { id: "PRY", name: "Paraguay" },
  { id: "PER", name: "Peru" },
  { id: "SUR", name: "Surinam" },
  { id: "URY", name: "Uruguay" },
  { id: "VEN", name: "Venezuela" },
];
